# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_dat/syncfifo_dist_dat.xci
# IP: The module: 'syncfifo_dist_dat' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_dat/syncfifo_dist_dat.xdc
# XDC: The top module name and the constraint reference have the same name: 'syncfifo_dist_dat'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_dat/syncfifo_dist_dat_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'syncfifo_dist_dat'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_dat/syncfifo_dist_dat.xci
# IP: The module: 'syncfifo_dist_dat' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_dat/syncfifo_dist_dat.xdc
# XDC: The top module name and the constraint reference have the same name: 'syncfifo_dist_dat'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_dat/syncfifo_dist_dat_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'syncfifo_dist_dat'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
