# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param chipscope.maxJobs 5
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.cache/wt [current_project]
set_property parent.project_path D:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/new/mem_test.v
  D:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/new/mem_trans_axi.v
  D:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/imports/imports/example_top.v
}
read_ip -quiet D:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_cmd/syncfifo_dist_cmd.xci
set_property used_in_implementation false [get_files -all d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_cmd/syncfifo_dist_cmd.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_cmd/syncfifo_dist_cmd_ooc.xdc]

read_ip -quiet D:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_dat/syncfifo_dist_dat.xci
set_property used_in_implementation false [get_files -all d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_dat/syncfifo_dist_dat.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/syncfifo_dist_dat/syncfifo_dist_dat_ooc.xdc]

read_ip -quiet D:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/vio_0/vio_0.xci
set_property used_in_implementation false [get_files -all d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/vio_0/vio_0.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc]

read_ip -quiet D:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200.xci
set_property used_in_implementation false [get_files -all d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200_board.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200.xdc]
set_property used_in_implementation false [get_files -all d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/constrs_1/new/example_top.xdc
set_property used_in_implementation false [get_files D:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_test/mig_7series_test.srcs/constrs_1/new/example_top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top example_top -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef example_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file example_top_utilization_synth.rpt -pb example_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
