# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/imports/example_top.xdc

# IP: ip/syncfifo_dist/syncfifo_dist.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==syncfifo_dist || ORIG_REF_NAME==syncfifo_dist} -quiet] -quiet
