# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_app/mig_7series_app.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200.xci
# IP: The module: 'clk_wiz_50_200' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_app/mig_7series_app.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50_200'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_app/mig_7series_app.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_app/mig_7series_app.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_app/mig_7series_app.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200.xci
# IP: The module: 'clk_wiz_50_200' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_app/mig_7series_app.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_app/mig_7series_app.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/self_learning/hulang/hulang001_plus/2_projects/mig_7series_app/mig_7series_app.srcs/sources_1/ip/clk_wiz_50_200/clk_wiz_50_200_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_50_200'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
